[package]
name = "viper"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.7"
oorandom = "11.1.3"
getrandom = "0.2.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
